/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TapLockNativeUnlock */

#ifndef _Included_TapLockNativeUnlock
#define _Included_TapLockNativeUnlock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TapLockNativeUnlock
 * Method:    nativeIsLocked
 * Signature: ()Z
 */
JNIEXPORT jstring JNICALL Java_TapLockNativeUnlock_nativeIsLocked
  (JNIEnv *, jobject);

/*
 * Class:     TapLockNativeUnlock
 * Method:    nativeUnlock
 * Signature: ()Z
 */
JNIEXPORT jstring JNICALL Java_TapLockNativeUnlock_nativeUnlock
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
